apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  labels: # replicaset labels
    app: nginx
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels: # selector labels
      tier: frontend
      app: nginx
  template:
    metadata:
      labels: # pod labels
        tier: frontend
        app: nginx
    spec:
      containers:
      - name: app1
        image: joindevops/app1:v1
---
apiVersion: v1
kind: Service
metadata:
  name: app1-service
spec:
  selector:
    tier: frontend
    app: nginx
  ports:
  - name: app1-serviceport
    protocol: TCP
    port: 80 #service port
    targetPort: 80 # container port